config/routes.rb
FiveWordMovies::Application.routes.draw do
  root to: 'static#welcome'

  resources :movies
  get '/welcome', to: 'static#welcome'
  get '/movie_search/:query', to: 'movie_search#show', format: 'json'

end

app/models/movie.rb
class Movie < ActiveRecord::Base
  attr_accessible :five_words, :title, :rotten_id

  def next_movie
    self.class.where('id > ?', self.id).order('id').first
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/movie_search_controller.rb
class MovieSearchController < ApplicationController
  require 'open-uri'
  require 'json'

  def show
    title = params[:query].gsub(/\s/, '+')
    limit = "&page_limit=3"
    response = open(base_query + title + limit).read

    respond_to do |format|
      format.json { render json: response }
    end
  end

  private

  def base_query
    begin
      api = YAML.load_file("#{Rails.root}/config/credentials.yml")['movie_api']
    rescue
      api = { 'api_key' => ENV['rotten_api_key'] }
    end

    "http://api.rottentomatoes.com/api/public/v1.0/movies.json?apikey=#{api['key']}&q="
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_filter :authenticate, except: :show

  def index
    @movies = Movie.order('created_at')
  end

  def show
    if params[:id] == 'random'
      redirect_to Movie.all.sample
    else
      @movie = find_movie
      @next = @movie.next_movie
    end
  end

  def new
    @movie = Movie.new
  end

  def create
    @movie = Movie.new(params[:movie])
    if @movie.save
      redirect_to movies_path
    else
      render :new
    end
  end

  def edit
    @movie = find_movie
  end

  def update
    @movie = find_movie
    if @movie.update_attributes(params[:movie])
      redirect_to movies_path
    else
      render :edit
    end
  end

  def destroy
    @movie = find_movie
    @movie.destroy

    redirect_to movies_path
  end

  private

  def find_movie
    Movie.find(params[:id])
  end

  def authenticate
    begin
      credentials = YAML.load_file("#{Rails.root}/config/credentials.yml")['basic_auth']
    rescue
      credentials = { 'user' => ENV['user'], 'pass' => ENV['pass'] }
    end

    authenticate_or_request_with_http_basic do |user, pass|
      user == credentials['user'] && pass == credentials['pass']
    end
  end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def welcome
    @first_movie = Movie.find(1, order: :created_at)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movie_search_helper.rb
module MovieSearchHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Five Word Movies</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>

  <%= csrf_meta_tags %>
</head>
<body>
  <div class="wrap">
    <div class="content">
      <%= yield %>
    </div>
  </div>
  <footer>

  </footer>
</body>
</html>

app/views/movies/_form.html.erb
<%= simple_form_for(@movie) do |form| %>
  <%= form.input :five_words, placeholder: 'Urban Horse Learns About Sex' %>
  <%= form.input :title, placeholder: 'Sex and the City', class: 'entry' %>
  <%= form.input :rotten_id, as: :hidden %>
  <ul class="results backend"></ul>
  <%= form.button :submit %>
<% end %>

app/views/movies/edit.html.erb
<%= render 'form' %>

app/views/movies/index.html.erb
<%= link_to 'New Movie', new_movie_path, class: 'new' %>

<ul>
  <% @movies.each do |movie| %>
    <li>
      <%= link_to movie.five_words, movie, class: 'five-words' %>
      <%= link_to 'Edit', edit_movie_path(movie), class: 'edit' %>
      <%= link_to 'Delete', movie, class:'delete', method: :delete, confirm: "Delete it? Really?" %>
    </li>
  <% end %>
</ul>

app/views/movies/new.html.erb
<%= render 'form' %>

app/views/movies/show.html.erb
<h1 class="five-words"><%= @movie.five_words %></h1>
<%= form_for @movie do |form| %>
  <div class="cta">
    <%= text_field_tag 'guess', nil, placeholder: 'Take a guess' %>
    <%= link_to "Next Movie", @next, class: 'next' %>
  </div>
  <%= hidden_field_tag nil, @movie.rotten_id, id: 'movie_rotten_id' %>
<% end %>
<ul class="results">
</ul>